wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1681006952.119703
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.9.5
      5: 0.14.0
      8:
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 20
correct:
  desc: null
  value:
  - 0.07990000000000126
  - 0.040450000000000645
  - 0.041450000000000674
  - 0.08090000000000129
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: mse
metric:
  desc: null
  value: mape
optimizer:
  desc: null
  value: rmsprop
predic:
  desc: null
  value:
  - 0.08134669065475464
  - 0.041117966175079346
  - 0.04202494025230408
  - 0.08223173022270203
