wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1681789262.987411
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.5
      5: 0.14.0
      8:
      - 3
      - 5
